development: &defaults
  :id: "ID"
  :sports_data_id: "Sports Data ID"
  :first_name: "First Name"
  :preferred_first: "First Name"
  :last_name: "Last Name"
  :preferred_last: "Last Name"
  :bat_hand: "Bat Hand"
  :throw_hand: "Throw Hand"
  :weight: "Weight"
  :height: "Height"
  :birthdate: "Birth Date"
  :birthstate: "Birth State"
  :birthcountry: "Birth Country"
  :highschool: "High School"
  :college: "College"
  :pro_debut: "Pro Debut"
  :position: "Position"
  :ab: "At Bats"
  :ap: "At Plate"
  :avg: "Average"
  :lob: "Left on Base"
  :pcount: "Pitch Count"
  :rbi: "RBI"
  :error: "Error"
  :abhr: "At Bats Per Home Run"
  :bip: "Balls in Play"
  :babip: "Batting Average on Balls In Play"
  :bbk: "Walks Per Strikeout"
  :bbpa: "Walks Per Plate Appearance"
  :gofo: "Ground Ball to Fly Ball Ratio"
  :iso: "Isolated Power"
  :obp: "On Base Percentage"
  :ops: "On Base plus Slugging Percentage"
  :seca: "Secondary Average"
  :slg: "Slugging Percentage"
  :tb: "Total Bases"
  :xbh: "Extra Base Hits"
  :h: "Hits"
  :s: "Singles"
  :d: "Doubles"
  :t: "Triples"
  :hr: "Home Runs"
  :bb: "Walks"
  :ibb: "Intentional Walks"
  :hbp: "Hit by Pitch"
  :unearned: "Unearned Runs"
  :earned: "Earned Runs"
  :total: "Total Runs Allowed"
  :klook: "Strikes Looking"
  :kswing: "Strikes Swinging"
  :ktotal: "Total Strikeouts"
  :ball: "Balls"
  :iball: "Intentional Balls"
  :dirtball: "Dirtballs"
  :foul: "Foul Balls"
  :po: "Pop Outs"
  :fo: "Foul Outs"
  :fidp: "Fly Outs into Double Plays"
  :go: "Ground Outs"
  :gidp: "Ground Outs Into Double Plays"
  :lo: "Line Outs"
  :lidp: "Line Outs Into Double Plays"
  :sacfly: "Sac Flys"
  :sachit: "Sacrifice Hits"
  :caught: "Caught Stealing"
  :stolen: "Stolen Bases"
  :start: "Games Started"
  :play: "Games Played"
  :finish: "Games Finished"
  :complete: "Games Completed"
  :ip_1: "Innings Pitched (Total Outs)"
  :ip_2: "Innings Pitch (Complete and Partial)"
  :bf: "Batters Faced"
  :era: "ERA"
  :k9: "Strikeouts per 9 innings"
  :whip: "WHIP"
  :win: "Wins"
  :loss: "Losses"
  :saves: "Saves"
  :qstart: "Quality Starts"
  :shutout: "Shutouts"
  :created_at: "Created At"
  :updated_at: "Updated At"

test:
  <<: *defaults

production:
  <<: *defaults

